disabled_rules:
  - trailing_whitespace
  - weak_delegate
  - todo
  - nslocalizedstring_key

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_self
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  # - missing_docs # enable later
  - multiline_arguments
  - multiline_parameters
  - no_extension_access_modifier
  # - no_grouping_extension # enable after refactoring RxDataSource extensions
  # - nslocalizedstring_key # enable after localization
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

excluded:
  - Pods
  - Generated
  - Templates
  - ../templates
  - GoodMealsTests

attributes:
  always_on_same_line: ["@objc", "@IBAction", "@NSManaged"]

closure_body_length:
  - 50 # warning
  - 60 # error

function_body_length:
  - 50 # warning
  - 60 # error

trailing_closure:
  only_single_muted_parameter: true

type_name:
    max_length:
        warning: 40
        error: 50

type_body_length:
- 300 # warning
- 400 # error

file_length:
- 400 # warning
- 500 # error

line_length:
 warning: 180
 ignores_comments: true

function_parameter_count:
- 5 # warning
- 7 # error

cyclomatic_complexity:
- 10 # warning
- 14 # error

identifier_name:
  min_length: 3
  excluded: ["id", "to", "in", "vm", "vc", "on", "of"] 
