platform :ios, '11.0'
inhibit_all_warnings!
use_frameworks!

def shared_pods
  pod 'RxSwift'
  pod 'RxCocoa'
end

target 'Events' do
  shared_pods
end  
  
target 'EventsTests' do
  shared_pods
  
  # Pods for testing
  pod 'RxBlocking'
  pod 'RxTest'
  pod 'OHHTTPStubs/Swift'
end
