platform :ios, '11.0'
inhibit_all_warnings!
use_frameworks!

def shared_pods
  pod 'RxSwift', '~> 4.4'
  pod 'RxCocoa', '~> 4.4'
  pod 'RxDataSources', '~> 3.1'
end

target 'Events' do
  shared_pods
end  
  
target 'EventsTests' do
  shared_pods
end