platform :ios, '11.0'
inhibit_all_warnings!
use_frameworks!

def shared_pods
  pod 'RxSwift', '~> 4.4'
  pod 'RxCocoa', '~> 4.4'
end

target 'Events' do
  shared_pods
end  
  
target 'EventsTests' do
  shared_pods
  
  # Pods for testing
  pod 'RxBlocking', '= 4.4.2'
  pod 'RxTest', '= 4.4.2'
end
